version: '3.8'

services:
  parking-system-dev:
    build:
      context: ..
      dockerfile: Dockerfile
      target: builder
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEBUG=true
      - LOG_LEVEL=DEBUG
    volumes:
      - ..:/app
      - parking_data_dev:/app/data
    command: ["python", "-m", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    depends_on:
      - redis-dev

  redis-dev:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data_dev:/data

volumes:
  parking_data_dev:
  redis_data_dev:
